version: '3.7'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
    volumes:
      - 'mysql_data:/var/lib/mysql'
    restart: always
    networks:
      - default

volumes:
  mysql_data: